# Auto Generated Dockerfile

FROM ballerina/ballerina-platform:0.982.0
LABEL maintainer="dev@ballerina.io"

COPY weather_forecasting_backend.balx /home/ballerina 

EXPOSE  9096

CMD ballerina run weather_forecasting_backend.balx
