---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "weather_forecasting_backend"
  name: "backend"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 9096
    protocol: "TCP"
    targetPort: 9096
  selector:
    app: "weather_forecasting_backend"
  type: "NodePort"
