# Auto Generated Dockerfile

FROM ballerina/ballerina-redis:0.982.0
LABEL maintainer="dev@ballerina.io"

COPY weather_forecasting_service.balx /home/ballerina 

EXPOSE  9100

CMD ballerina run weather_forecasting_service.balx
