# Auto Generated Dockerfile

FROM ballerina/ballerina-platform:0.980.1
LABEL maintainer="dev@ballerina.io"

COPY weather_forecasting_backend.balx /home/ballerina 

EXPOSE  9095

CMD ballerina run weather_forecasting_backend.balx
